

enum MSG_TYPE
{
	// Client messages                   Server response:
	MSG_TYPE_QUERY_STREAM_STATUS,     // -> MSG_TYPE_STREAM_IS_{STARTED,STOPPED}
	MSG_TYPE_QUERY_IMAGE_INFO,        // -> MSG_TYPE_IMAGE_INFO_RESPONSE
	MSG_TYPE_QUERY_SUPPORTED_FORMATS, // -> MSG_TYPE_SUPPORTED_FORMATS_RESPONSE
	MSG_TYPE_USE_FORMAT,              // -> MSG_TYPE_IMAGE_INFO_RESPONSE
	MSG_TYPE_START_STREAM,            // -> MSG_TYPE_STREAM_IS_STARTED
	MSG_TYPE_PAUSE_STREAM,            // -> MSG_TYPE_STREAM_IS_STOPPED

	// Server messages
	MSG_TYPE_STREAM_IS_STARTED,
	MSG_TYPE_STREAM_IS_STOPPED,
	MSG_TYPE_IMAGE_INFO_RESPONSE,
	MSG_TYPE_SUPPORTED_FORMATS_RESPONSE,
	MSG_TYPE_FRAME,

	// Both
	MSG_TYPE_ERROR_OCCURRED
};

struct image_info
{
	uint32_t width;
	uint32_t height;
	uint32_t fmt;
}

const in_port_t DEFAULT_PORT = 32123;

